// frontend/src/components/FileForm.jsx
import { AppContext } from "../App";
import React, { useContext } from "react";

function FileForm() {
  const { latestPost, setLatestPost } = useContext(AppContext);

  function handleSubmit(event) {
    event.preventDefault();

    const data = new FormData();

    data.append("post[title]", event.target.title.value);
    data.append("post[image]", event.target.image.files[0]);

    submitToAPI(data);
  }

  function submitToAPI(data) {
    fetch("http://localhost:3000/posts", {
      method: "POST",
      body: data,
    })
      .then((res) => res.json())
      .then((data) => {
        console.log("data", data);
        setLatestPost(data.image_url);
      })
      .catch((err) => console.error(err));
  }

  return (
    <div>
      <h1>File Form</h1>
      <form onSubmit={(e) => handleSubmit(e)}>
        <label htmlFor="title">Title</label>
        <input type="text" name="title" id="title" />
        <br />

        <label htmlFor="image">Image</label>
        <input type="file" name="image" id="image" />
        <br />

        <button type="submit">Create post</button>
      </form>
    </div>
  );
}

export default FileForm;

// frontend-vue/src/components/FileForm.vue
<script setup lang="ts">
import { setLatestPost } from "./ImageService";

function handleSubmit(event: Event) {
  event.preventDefault();

  const data = new FormData();
  console.log(data);
  data.append("post[title]", event.target.title.value);
  data.append("post[image]", event.target.image.files[0]);
  // data.append("title", event.target.title.value);
  // data.append("image", event.target.image.files[0]);
  console.log(data);
  submitToAPI(data);
}

function submitToAPI(data: FormData) {
  fetch("http://localhost:3000/posts", {
    method: "POST",
    body: data,
  })
    .then((res) => res.json())
    .then((data) => setLatestPost(data.id))
    .catch((err) => console.error(err));
}
</script>

<template>
  <div>
    <h1>FileForm</h1>
    <form @submit="handleSubmit">
      <label for="title">Title</label>
      <input type="text" name="title" id="title" />
      <br />

      <label for="image">Image</label>
      <input type="file" name="image" id="image" />
      <br />

      <button type="submit">Create post</button>
    </form>
  </div>
</template>

<style></style>
