// frontend/src/components/LatestImage.jsx
import { AppContext } from "../App";
import React, { useContext, useEffect } from "react";

function LatestImage() {
  const { latestPost, setLatestPost } = useContext(AppContext);

  useEffect(() => {
    fetch("http://localhost:3000/latest")
      .then((res) => res.json())
      .then((data) => setLatestPost(data.image_url))
      .catch((err) => console.error(err));
  }, [latestPost]);

  return (
    <div>
      <img src={latestPost} alt="latest post" className="latest-image" />
    </div>
  );
}

export default LatestImage;

// frontend-vue/src/components/LatestImage.vue
<script setup lang="ts">
import { watch, ref, onMounted } from "vue";
import { latestPost } from "./ImageService";

const imageUrl = ref();

watch(
  () => latestPost.value,
  () => {
    download();
  }
);

onMounted(() => download());

function download() {
  fetch("http://localhost:3000/latest")
    .then((res) => res.json())
    .then((data) => (imageUrl.value = data.image_url))
    .catch((err) => console.error(err));
}
</script>

<template>
  <div>
    <img :src="imageUrl" alt="latest post" />
  </div>
</template>

<style></style>
